server:
  port: 8501
spring:
  application :
    name: account-service
  data:
    cassandra:
      keyspace-name: sp_cloud_account
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists

eureka:
  client:
    instance:
      hostname: localhost
    service-url:
      defaultZone: http://localhost:8500/eureka/